### ISSUE TITLE
别看了 我是傻逼

### ISSUE THREAD

**Issue by lgc2333** [noneplugin/nonebot-plugin-imageutils#16]
```py
Traceback (most recent call last):
  File "D:\Coding\python\nonebot-plugin-picmcstat\debug\debug.py", line 10, in <module>
    asyncio.run(main())
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\Coding\python\nonebot-plugin-picmcstat\debug\debug.py", line 7, in main
    pic = await draw("hypixel.nettt", "je")
  File "D:\Coding\python\nonebot-plugin-picmcstat\nonebot_plugin_picmcstat\draw.py", line 138, in draw
    return draw_error(e, svr_type)
  File "D:\Coding\python\nonebot-plugin-picmcstat\nonebot_plugin_picmcstat\draw.py", line 123, in draw_error
    return build_img(
  File "D:\Coding\python\nonebot-plugin-picmcstat\nonebot_plugin_picmcstat\draw.py", line 55, in build_img
    bg.draw_text(
  File "D:\Coding\python\nonebot-plugin-picmcstat\venv\virtualenvs\nonebot-plugin-picmcstat-SrjGE_up-py3.10\lib\site-packages\nonebot_plugin_imageutils\build_image.py", line 497, in draw_text
    text2img.draw_on_image(self.image, (int(x), int(y)))
  File "D:\Coding\python\nonebot-plugin-picmcstat\venv\virtualenvs\nonebot-plugin-picmcstat-SrjGE_up-py3.10\lib\site-packages\nonebot_plugin_imageutils\text2image.py", line 429, in draw_on_image
    char.draw_on(img, (int(x), int(y)))
  File "D:\Coding\python\nonebot-plugin-picmcstat\venv\virtualenvs\nonebot-plugin-picmcstat-SrjGE_up-py3.10\lib\site-packages\nonebot_plugin_imageutils\text2image.py", line 67, in draw_on
    draw.text(
  File "D:\Coding\python\nonebot-plugin-picmcstat\venv\virtualenvs\nonebot-plugin-picmcstat-SrjGE_up-py3.10\lib\site-packages\PIL\ImageDraw.py", line 510, in text
    stroke_ink = getink(stroke_fill) if stroke_fill is not None else ink
  File "D:\Coding\python\nonebot-plugin-picmcstat\venv\virtualenvs\nonebot-plugin-picmcstat-SrjGE_up-py3.10\lib\site-packages\PIL\ImageDraw.py", line 448, in getink
    ink, fill = self._getink(fill)
  File "D:\Coding\python\nonebot-plugin-picmcstat\venv\virtualenvs\nonebot-plugin-picmcstat-SrjGE_up-py3.10\lib\site-packages\PIL\ImageDraw.py", line 130, in _getink
    ink = self.draw.draw_ink(ink)
TypeError: color must be int or tuple
```

**Comment by lgc2333** [comment]
`BuildImage.draw_text` 这个参数的类型注解是
```py
stroke_fill: Optional[ColorType] = None
```

```py
ColorType = Union[str, Tuple[int, int, int], Tuple[int, int, int, int]]
```

**Comment by lgc2333** [comment]
我是傻逼 我自己的代码问题
