### ISSUE TITLE
cannot import name 'cache' from 'functools'

### ISSUE THREAD

**Issue by tyx3** [noneplugin/nonebot-plugin-imageutils#21]
这是什么问题
02-18 00:39:24 [ERROR] nonebot | Failed to import "nonebot_plugin_imageutils"
Traceback (most recent call last):
  File "bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/zhenxun_bot/extensive_plugin/nonebot_plugin_imageutils/__init__.py", line 1, in <module>
    from .build_image import BuildImage
  File "/root/zhenxun_bot/extensive_plugin/nonebot_plugin_imageutils/build_image.py", line 14, in <module>
    from .text2image import Text2Image
  File "/root/zhenxun_bot/extensive_plugin/nonebot_plugin_imageutils/text2image.py", line 3, in <module>
    from functools import cache
ImportError: cannot import name 'cache' from 'functools' (/usr/lib/python3.8/functools.py

**Comment by Zmincrix** [comment]
同

**Comment by MeetWq** [comment]
不小心用了 python 3.9 才有的东西，目前已修复
